/**
 * @author 赵亚一
 * @comment 重建
 * @date 2016-7-8 下午11:13:02
 */
Ext.define('KJXM.model.ReconstructionFunding', {
    extend: 'Ext.data.Model',
    fields: [
{name: 'xmmc',  type: 'string'},
{name: 'htze1',  type: 'float'},
{name: 'htze2',  type: 'float'},
{name: 'htze3',  type: 'float'},
{name: 'htze4',  type: 'float'},
{name: 'bkje1',  type: 'float'},
{name: 'bksj1',  type: 'date'},
{name: 'bkje2',  type: 'float'},
{name: 'bksj2',  type: 'date'},
{name: 'bkje3',  type: 'float'},
{name: 'bksj3',  type: 'date'},
{name: 'bkje4',  type: 'float'},
{name: 'bksj4',  type: 'date'},
{name: 'bkje5',  type: 'float'},
{name: 'bksj5',  type: 'date'},
{name: 'bkje6',  type: 'float'},
{name: 'bksj6',  type: 'date'},
{name: 'bkje7',  type: 'float'},
{name: 'bksj7',  type: 'date'},
{name: 'bkje8',  type: 'float'},
{name: 'bksj8',  type: 'date'},
{name: 'bkje9',  type: 'float'},
{name: 'bksj9',  type: 'date'},
{name: 'bkje10',  type: 'float'},
{name: 'bksj10',  type: 'date'},
{name: 'bkje11',  type: 'float'},
{name: 'bksj11',  type: 'date'},
{name: 'bkje12',  type: 'float'},
{name: 'bksj12',  type: 'date'},
{name: 'bkje13',  type: 'float'},
{name: 'bksj13',  type: 'date'},
{name: 'bkje14',  type: 'float'},
{name: 'bksj14',  type: 'date'},
{name: 'bkje15',  type: 'float'},
{name: 'bksj15',  type: 'date'},
{name: 'bkje16',  type: 'float'},
{name: 'bksj16',  type: 'date'},
{name: 'zb1',  type: 'string'},
{name: 'zb2',  type: 'string'},
{name: 'zb3',  type: 'string'},
{name: 'zb4',  type: 'string'},
{name: 'zb5',  type: 'string'},
{name: 'zb6',  type: 'string'},
{name: 'zb7',  type: 'string'},
{name: 'zb8',  type: 'string'},
{name: 'zb9',  type: 'string'},
{name: 'zb10',  type: 'string'},
{name: 'zb11',  type: 'string'},
{name: 'zb12',  type: 'string'},
{name: 'zb13',  type: 'string'},
{name: 'zb14',  type: 'string'},
{name: 'zb15',  type: 'string'},
{name: 'zb16',  type: 'string'}
    ]
});